r"""Emit the reversibility grid (Figure 2) from the run data: three panels, two
applications, generated so the figure cannot drift from the measurement.

  (a) Magento orders    out/e1_grid.json
  (b) Magento reviews   out/e1_grid_reviews.json
  (c) Postmill comments out/e2_grid_postmill.json

The star is computed, not typed: any verb whose measured cells include both a
reversible and an irreversible outcome is marked on its irreversible cells. Today
that is Postmill's downvote; on Magento no verb changes class across states, and
the figure would say so by marking nothing.

The tints are named grid* on purpose. figstyle.tex owns revg/irrr as the
document's semantic colours; redefining those here once silently repainted every
later figure.

  out: fig_grid.tex
"""
import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]; OUT = ROOT / 'out'

def load(name):
    f = OUT / name
    if not f.exists(): return []
    return [r for r in json.loads(f.read_text()) if r.get('cell_role') != 'POSITIVE_CONTROL']

PANELS = [
    dict(tag='(a) Magento \\emph{orders}', rows=load('e1_grid.json'),
         verbs=['hold', 'cancel', 'ship', 'invoice', 'send_email', 'reorder'],
         states=[('pending', 'Pend.'), ('processing_shipped', 'P.ship'),
                 ('processing_invoiced', 'P.inv'), ('on_hold', 'Hold'),
                 ('complete', 'Compl.'), ('canceled', 'Canc.')]),
    dict(tag='(b) Magento \\emph{reviews}', rows=load('e1_grid_reviews.json'),
         verbs=['delete', 'approve', 'reject', 'unpublish'],
         states=[('approved', 'Appr.'), ('pending', 'Pend.'), ('not_approved', 'Not appr.')]),
    dict(tag='(c) Postmill \\emph{comments}', rows=load('e2_grid_postmill.json'),
         verbs=['upvote', 'downvote', 'edit', 'delete'],
         states=[('none', 'no vote'), ('upvoted', 'upvoted')]),
]

CELL = {
    ('MEASURED', True):    r'\cellcolor{gridrev}\textbf{R}',
    ('MEASURED', False):   r'\cellcolor{gridirr}\textbf{I}',
    'NOT_OFFERED':         r'\cellcolor{gridoff}--',
    'OFFERED_BUT_REFUSED': r'\cellcolor{gridnop}$\equiv$',
    'OFF_PAGE_EFFECT':     r'\cellcolor{gridext}$\circ$',
}
MISSING = r'\cellcolor{gridoff}--'

def panel(p):
    by = {(r['verb'], r['state']): r for r in p['rows']}
    # verbs whose class flips across the states in which they act
    flips = set()
    for v in p['verbs']:
        cls = {r['reversible'] for (vv, _), r in by.items()
               if vv == v and r.get('outcome') == 'MEASURED'}
        if cls == {True, False}: flips.add(v)
    lines = []
    for v in p['verbs']:
        cells = []
        for key, _ in p['states']:
            r = by.get((v, key))
            g = CELL.get((r.get('outcome'), r.get('reversible')), CELL.get(r.get('outcome'))) if r else None
            g = g or MISSING
            if v in flips and r and r.get('outcome') == 'MEASURED' and r['reversible'] is False:
                g += r'$^{\star}$'
            cells.append(g)
        warn = 'yes' if any(r.get('gate_warn') for (vv, _), r in by.items() if vv == v) else 'no'
        lines.append('\\texttt{%s} & %s & %s \\\\' % (v.replace('_', r'\_'), ' & '.join(cells), warn))
    n = len(p['states'])
    head = (f"\\begin{{tabular}}[t]{{@{{}}l {'c'*n} c@{{}}}}\n"
            f"\\multicolumn{{{n+2}}}{{@{{}}l}}{{{p['tag']}}} \\\\\n\\toprule\n"
            f"& {' & '.join(t for _, t in p['states'])} & \\hspace{{4pt}}warns? \\\\\n\\midrule\n")
    return head + '\n'.join(lines) + '\n\\bottomrule\n\\end{tabular}', flips, by

blocks, flips_all, n_measured = [], {}, 0
for p in PANELS:
    tex, flips, by = panel(p)
    blocks.append(tex); flips_all[p['tag']] = flips
    n_measured += sum(1 for r in by.values() if r.get('outcome') == 'MEASURED')

magento_flips = flips_all[PANELS[0]['tag']] | flips_all[PANELS[1]['tag']]
postmill_flips = flips_all[PANELS[2]['tag']]
# the caption marks flips and the body claims Magento has none; refuse if the data moved
assert not magento_flips, f'a Magento verb now flips class: {magento_flips}'
assert postmill_flips == {'downvote'}, f'Postmill flips are now {postmill_flips}'

body = r"""% Generated by scripts/32_grid_figure.py -- do not hand-edit.
\definecolor{gridrev}{RGB}{223,240,216}
\definecolor{gridirr}{RGB}{248,215,218}
\definecolor{gridoff}{RGB}{238,238,238}
\definecolor{gridnop}{RGB}{226,232,240}
\definecolor{gridext}{RGB}{248,244,222}
\begin{figure*}[t]
\centering
\footnotesize
\setlength{\tabcolsep}{3pt}
""" + '\\hfill\n'.join(blocks) + r"""
\caption{Measured reversibility, write verb by object state (""" + f"{n_measured}" + r""" measured cells).
\colorbox{gridrev}{\textbf{R}} an inverse restored the state;
\colorbox{gridirr}{\textbf{I}} none did;
\colorbox{gridoff}{--} not offered;
\colorbox{gridnop}{$\equiv$} offered, a no-op;
\colorbox{gridext}{$\circ$} effect leaves the page;
$\star$ class changes with state.
\emph{warns?}: warning text before commit (C1, Table~\ref{tab:calib}).}
\label{fig:grid}
\end{figure*}
"""
assert not re.search(r'@[A-Z]+@', body)
(ROOT / 'fig_grid.tex').write_text(body)
print(f'wrote fig_grid.tex: {n_measured} measured cells, flips = {sorted(postmill_flips)} (Postmill only)')
