r"""Emit the page-1 motivation figure from the measured credit-memo cell.

A taxonomy that assigns reversibility from the verb calls `invoice` compensable,
because the application names a compensating action and puts it on the page. We
submit it, and the order does not come back -- it advances to a third state.

Laid out left-to-right: three status boxes are the whole figure, so it costs
about a fifth of the vertical space the stacked version did.

  out: fig_motivation.tex   (\input by main.tex)
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERB, STATE = 'invoice', 'pending'

rows = json.loads((ROOT / 'out/e1_grid.json').read_text())
r = next(x for x in rows if (x['verb'], x['state']) == (VERB, STATE)
         and x['outcome'] == 'MEASURED')

inv, gained, lost = r['inverse_taken'], r['gained'], r['lost']
commit = r.get('inverse_commit_control')
s0, s1, s2 = r['pre_status'], r['post_status'], r['undo_status']

# The figure asserts four things. The previous version drew a compensation that
# was never submitted, because nothing here checked that it had been.
assert inv in gained,             f'{inv!r} is not among the newly-gained controls {gained}'
assert r.get('inverse_committed'), 'the inverse was not committed; this figure would be fiction'
assert r['reversible'] is False,  'cell no longer grades irreversible'
assert s1 != s0,                  'the write did not change the status'
assert s2 not in (s0, s1),        'the compensation no longer lands in a third state'

clean = lambda bs: [b for b in bs if not b.startswith('\ue626')]   # Magento's Back chevron
pre = clean(r['pre_buttons'])
undo_lost = sorted(set(clean(r['post_buttons'])) - set(clean(r['undo_buttons'])))
esc = lambda t: t.replace('_', r'\_').replace('&', r'\&')
show = [c for c in ('Cancel', 'Invoice', 'Ship') if c in pre]

TEMPLATE = r"""% Generated by scripts/36_motivation_figure.py -- do not hand-edit.
\begin{figure}[t]
\centering
\begin{tikzpicture}[
  font=\footnotesize,
  stbox/.style={rounded corners=1.5pt, line width=.6pt, inner xsep=3pt,
                inner ysep=3pt, minimum width=1.4cm, align=center,
                draw=neutg, fill=lightg!50, text=black},
  flow/.style={-{Straight Barb[length=3pt,width=3.6pt]}, line width=.7pt},
  lbl/.style={midway, above=1pt, font=\footnotesize, align=center},
  under/.style={anchor=north, font=\footnotesize, align=center,
                text width=2.5cm, neutg},
]
\node[stbox] (a) at (0,0)    {@S0@};
\node[stbox] (b) at (2.75,0) {@S1@};
\node[stbox, draw=irrr, fill=irrr!12, text=irrr] (c) at (5.85,0) {@S2@};
\draw[flow, neutg] (a) -- node[lbl, text=black] {\texttt{@VERB@}} (b);
\draw[flow, irrr]  (b) -- node[lbl, text=irrr] {@INV@} (c);
% what an undo would restore: the order back to its prior state
\draw[flow, revg, dashed] (b.north) .. controls +(0,0.6) and +(0,0.6) ..
  node[pos=0.5, above=1pt, text=revg] {what an undo would restore}
  node[pos=0.5, text=irrr, font=\small\bfseries, fill=white, inner sep=0.5pt] {$\times$}
  (a.north);
\node[under, text width=2.3cm] at (0,-0.36)    {offers @SHOW@};
\node[under] at (2.75,-0.36) {$-$\,@LOST@\\ $+$\,\textbf{@INV@}};
\node[under, text=irrr, text width=2.35cm] at (5.85,-0.36) {$-$\,@ULOST@: \textbf{a third state}};
\end{tikzpicture}
\caption{Compensable is not reversible. Submitting \texttt{@INV@}, Magento's
compensation for \texttt{@VERB@}, moves the order to a third state, not back to
@S0@ (dashed).}
\label{fig:motivation}
\end{figure}
"""

body = TEMPLATE
for tok, val in (('@S0@', esc(s0)), ('@S1@', esc(s1)), ('@S2@', esc(s2)),
                 ('@VERB@', esc(VERB)), ('@INV@', esc(inv)), ('@COMMIT@', esc(commit)),
                 ('@SHOW@', esc(', '.join(show))), ('@LOST@', esc(', '.join(lost))),
                 ('@ULOST@', esc(', '.join(undo_lost)))):
    body = body.replace(tok, val)
assert '@' not in body.replace(r'\@', ''), 'unsubstituted token remains'
assert show and lost and undo_lost, f'empty affordance list: {show=} {lost=} {undo_lost=}'
(ROOT / 'fig_motivation.tex').write_text(body)
print('wrote fig_motivation.tex')
print(f"  {VERB} x {STATE}:  {s0} -> {s1} -> ({inv} + {commit}) -> {s2}")
