r"""Emit the second-application table and its 2x2 from out/e2_grid_postmill.json.

Deliberately does NOT compute kappa. Postmill renders no confirmation anywhere in
this grid, so the rated `warned` variable is constant; kappa is then undefined
(or degenerate) and printing one would read as "calibrates badly" when the fact
is that there is no signal to calibrate. The 2x2 is the result.

  out: tab_e2.tex
"""
import json, sys, collections
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
G = json.loads((ROOT / 'out/e2_grid_postmill.json').read_text())
ctl = [r for r in G if r.get('cell_role') == 'POSITIVE_CONTROL']
rows = [r for r in G if r.get('cell_role') != 'POSITIVE_CONTROL']
meas = [r for r in rows if r['outcome'] == 'MEASURED']

assert ctl, 'no positive control in the record'
assert all(r.get('reversible') is True for r in ctl), \
    'a positive control failed: the cells it batches are not evidence'

VERBS  = ['upvote', 'downvote', 'edit', 'delete']
STATES = [('none', 'no vote'), ('upvoted', 'upvoted')]
GLYPH = {(True,): r'\cellcolor{gridrev}\textbf{R}',
         (False,): r'\cellcolor{gridirr}\textbf{I}'}
by = {(r['verb'], r['state']): r for r in rows}

def cell(v, s):
    r = by.get((v, s))
    if r is None or r['outcome'] == 'HARNESS_ERROR':
        return r'\cellcolor{gridoff}$\cdot$'
    if r['outcome'] == 'NOT_OFFERED':
        return r'\cellcolor{gridoff}--'
    if r['outcome'] != 'MEASURED':
        return r'\cellcolor{gridoff}$\cdot$'
    return GLYPH[(r['reversible'],)]

lines = []
for v in VERBS:
    cells = ' & '.join(cell(v, s) for s, _ in STATES)
    ms = [r for (vv, _), r in by.items() if vv == v and r['outcome'] == 'MEASURED']
    rev = ('yes' if all(r['reversible'] for r in ms) else 'no') if ms else 'n/a'
    warn = 'yes' if any(r.get('gate_warn') for (vv, _), r in by.items() if vv == v) else 'no'
    lines.append(f"\\texttt{{{v}}} & {cells} & {warn} & {rev} \\\\")

irr = [r for r in meas if r['reversible'] is False]
rev = [r for r in meas if r['reversible'] is True]
warned = lambda rs: sum(1 for r in rs if r.get('gate_warn'))
tab = dict(irr=len(irr), irr_warned=warned(irr), rev=len(rev), rev_warned=warned(rev))

tex = r"""% Generated by scripts/40_e2_table.py -- do not hand-edit.
\begin{table}[htbp]
\caption{The same probe on a second application (Postmill). """ + \
f"{len(meas)} measurable cells, {len(ctl)} positive controls, all recovered." + r"""
\colorbox{gridrev}{\textbf{R}} reversible, \colorbox{gridirr}{\textbf{I}} not,
\colorbox{gridoff}{--} not offered in that state. Not pooled with
Figure~\ref{fig:grid}: the two applications are the contrast.}
\label{tab:e2}
\small
\setlength{\tabcolsep}{5pt}
\begin{tabular}{@{}l cc | cc@{}}
\toprule
\textit{state} & """ + ' & '.join(t for _, t in STATES) + r""" & warns? & rev.? \\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
(ROOT / 'tab_e2.tex').write_text(tex)
print('wrote tab_e2.tex')
print(f"  measured {len(meas)}  irreversible {tab['irr']}  reversible {tab['rev']}")
print(f"  warned among irreversible: {tab['irr_warned']}/{tab['irr']}")
print(f"  warned among reversible  : {tab['rev_warned']}/{tab['rev']}   (false alarms)")
print(f"  positive controls: {len(ctl)}, all reversible")
print(f"\n  kappa deliberately NOT computed: the warned column is constant "
      f"({tab['irr_warned'] + tab['rev_warned']} of {len(meas)} cells warned)")
